---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-infra-tenant
  serviceAccountName: kustomize-controller
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  wait: true
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  path: ./tenants/apps
