---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ENVIRONMENT: "prod"
  VARIANT: "k0s"
  TIMEZONE: "America/Toronto"
  INTERNAL_DOMAIN: "cleroux.dev"
  EXTERNAL_DOMAIN: "cleroux.com"
