apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-system
spec:
  serviceAccountName: flux-apps
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  path: deploy/${ENVIRONMENT}
