---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ENVIRONMENT: "staging"
  TIMEZONE: "America/Toronto"
  INTERNAL_DOMAIN: "cleroux.dev"
  EXTERNAL_DOMAIN: "cleroux.com"

  METALLB_IPV4_LB_RANGE: "172.18.255.200-172.18.255.250"
  METALLB_IPV4_K8S_GATEWAY_ADDR: "172.18.255.200"
