---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-system

resources:
  - ./namespace.yaml
  - ./source.yaml
  - ./ks.yaml

labels:
  - pairs:
      toolkit.fluxcd.io/tenant: infra

secretGenerator:
  - name: sops-age
    files:
      - ../../age.agekey
  - name: flux-infra
    files:
      - password=../../github_token
    literals:
      - username=git

configurations:
  - kustomizeconfig.yaml
