---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-infra
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: flux-infra
  url: https://github.com/cleroux-dev-homelab/flux-infra.git
